config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    collection do
      get 'top'
    end
    member do
      get 'chef'
    end

    resources :reviews, only: [:new, :create] 

  end
   
  resources :reviews, only: [:destroy]

  root to: 'restaurants#index'  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :chef]

  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy
    
    respond_to do |format|
      format.html { redirect_to restaurants_url, status: :see_other, notice: 'Restaurant was successfully destroyed.' }
    end
  end

  def top
    @restaurants = Restaurant.where(rating: 5)
  end

  def chef
   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :rating, :chef_name)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]

  def new
      @review = Review.new 
  end

  def create
      @review = Review.new(review_params)
      @review.restaurant = @restaurant
       if    @review.save
          redirect_to restaurant_path(@restaurant)
       else   
          render :new
      end
  end

  def destroy
      @review = Review.find(params[:id])
      @review.destroy

      respond_to do |format|
        format.html { redirect_to restaurant_path(@review.restaurant), status: :see_other, notice: 'Review was successfully destroyed.' }
      end
      
  end
  
  private 
  def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
      params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RevRestaurants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class='container'>  
      <%= yield %>
    </div>  
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :rating %>
    <%= f.input :chef_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
  <p>
    <strong>Name:</strong>
    <%= restaurant.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= restaurant.address %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= restaurant.rating %>
  </p>

  <p>
    <strong>Chef name:</strong>
    <%= restaurant.chef_name %>
  </p>

</div>

app/views/restaurants/chef.html.erb
<h1> El chef del <%= @restaurant.name %> es <%= @restaurant.chef_name  %> </h1>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Show this restaurant", @restaurant %> |
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Restaurants</h1>

<table class='table'>
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Dirección</th>
      <th scope="col">Rating</th>
      <th scope="col">Chef</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.rating %></td>
        <td><%= restaurant.chef_name %></td>
        <td><%= link_to 'Mostrar', restaurant %></td>
        <td><%= link_to 'Editar', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Eliminar', restaurant, data: {turbo_method: :delete, turbo_confirm: 'Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @restaurant.rating %>
</p>

<p>
  <strong>Chef:</strong>
  <%= @restaurant.chef_name %>
</p>


  <strong>Review:</strong> <small> <%= link_to 'Deja tu comentario', new_restaurant_review_path(@restaurant) %></small>
  <% @restaurant.reviews.each do |review| %>
    <p><%= review.content %> <small> <%= link_to 'Eliminar', review_path(review),  data: {turbo_method: :delete, turbo_confirm: 'Estás seguro?'} %> </small></p>
  <% end  %>


<%= link_to 'Editar', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Volver', restaurants_path %>

app/views/restaurants/top.html.erb
<h1> Nuestros mejores restaurantes </h1>

    <ul>
        <% @restaurants.each do |restaurant| %>
            <li>
                <%= restaurant.name %> <%= '*' * restaurant.rating  %>
            </li>
        <% end %>

    </ul>

app/views/reviews/_form.html.erb
<%= form_for([@review.restaurant, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :restaurant %><br />
    <%= f.text_field :restaurant %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', [@review.restaurant, @review] %> |
<%= link_to 'Back', restaurant_reviews_path(@review.restaurant) %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Restaurant</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.content %></td>
    <td><%= review.restaurant %></td>
    <td><%= link_to 'Show', [review.restaurant, review] %></td>
    <td><%= link_to 'Edit', edit_restaurant_review_path(review.restaurant, review) %></td>
    <td><%= link_to 'Destroy', [review.restaurant, review],  data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_restaurant_review_path(params[:restaurant_id]) %>

app/views/reviews/new.html.erb
<div class='container'>

    <h2> Agregar un comentario del restaurant <%= @restaurant.name %> </h2>
    <div class='form-group'>
        
        <%= simple_form_for [@restaurant, @review] do |form|  %>
            <%= form.label :Review, class: 'form-label'  %>
            <%= form.text_area :content, label: 'Deja tu comentario', class: 'form-control'  %>
            <%= form.submit %>

        <% end %>
    </div>
</div>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @review.content %>
</p>

<p>
  <b>Restaurant:</b>
  <%= @review.restaurant %>
</p>


<%= link_to 'Edit', edit_restaurant_review_path(@review.restaurant, @review) %> |
<%= link_to 'Back', restaurant_reviews_path(@review.restaurant) %>